# Generated by Django 2.1 on 2018-09-21 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp', verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp', null=True, verbose_name='Last updated at')),
                ('content', models.CharField(max_length=255, verbose_name='Question content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp', verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp', null=True, verbose_name='Last updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Selected rank')),
                ('trial_round', models.PositiveIntegerField(help_text='Number of round of questions', verbose_name='Trial round')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranker.Question', verbose_name='Question')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranker.Ranking', verbose_name='Ranking')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='entries',
            field=models.ManyToManyField(through='ranker.RankingEntry', to='ranker.Question'),
        ),
    ]
