# Generated by Django 2.1 on 2018-09-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0002_auto_20180929_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='category_stage1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ranking_stage1', to='ranker.Category', verbose_name='Stage 1 category (randomly chosen)'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='category_stage2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ranking_stage2', to='ranker.Category', verbose_name='Stage 2 category (randomly chosen)'),
        ),
    ]
