# Generated by Django 2.1 on 2018-09-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0004_auto_20180930_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingentry',
            old_name='trial_stage',
            new_name='stage',
        ),
    ]
