# Generated by Django 2.1 on 2018-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0005_auto_20180930_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', help_text='Provide if you want to enter the draw or to receive paper(s) about this study.', max_length=254, verbose_name='E-mail address')),
                ('draw', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I want to take part in the draw')),
                ('paper', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I want to receive the paper(s) about this study')),
            ],
            options={
                'verbose_name': 'Draw entry',
                'verbose_name_plural': 'Draw entries',
            },
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'Person ranking', 'verbose_name_plural': 'Person rankings'},
        ),
        migrations.AlterField(
            model_name='ranking',
            name='stage',
            field=models.PositiveIntegerField(default=0, help_text='0 - not started, 1 - answered email, 2 - first set completed, 3 - second set completed, 4 - answered demographic', verbose_name='Completion stage'),
        ),
    ]
