# Generated by Django 2.1 on 2018-10-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0006_auto_20181004_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='comp_research_involvement',
            field=models.CharField(choices=[('none', 'I have no involvement.'), ('rare', "I sometimes read results from studies or go to presentations but don't do any research myself."), ('regular', "I regularly read results from studies or go to presentations but don't do any research myself."), ('occasional', 'I occasionally dabble in computing education research myself.'), ('primary', 'Computing education research is my primary occuption.')], default='', help_text='Select the option that best describes you.', max_length=50, verbose_name='How involved you are personally in computing education research?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='daily_broadband',
            field=models.CharField(choices=[('none', 'None'), ('quarter', 'Less than a quarter'), ('quertertothree', 'One quarter to three quarters'), ('morethanthree', 'More than three quarters')], default='', max_length=50, verbose_name='What fraction of your learners has daily access to high-speed / broadband internet?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='daily_home_computer',
            field=models.CharField(choices=[('none', 'None'), ('quarter', 'Less than a quarter'), ('quertertothree', 'One quarter to three quarters'), ('morethanthree', 'More than three quarters')], default='', max_length=50, verbose_name='What fraction of your learners has daily access to laptop or computer at home?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='daily_lowspeed',
            field=models.CharField(choices=[('none', 'None'), ('quarter', 'Less than a quarter'), ('quertertothree', 'One quarter to three quarters'), ('morethanthree', 'More than three quarters')], default='', max_length=50, verbose_name='What fraction of your learners has daily access to only low-speed internet?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='daily_school_computer',
            field=models.CharField(choices=[('none', 'None'), ('quarter', 'Less than a quarter'), ('quertertothree', 'One quarter to three quarters'), ('morethanthree', 'More than three quarters')], default='', max_length=50, verbose_name='What fraction of your learners has daily access to school or library computer?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='daily_smartphone',
            field=models.CharField(choices=[('none', 'None'), ('quarter', 'Less than a quarter'), ('quertertothree', 'One quarter to three quarters'), ('morethanthree', 'More than three quarters')], default='', max_length=50, verbose_name='What fraction of your learners has daily access to tablet or smartphone?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_adults',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching adults in workplaces (e.g. staff training)?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_adults_free_range',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching adults in free-range programs (i.e. outside traditional classrooms)?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_children_free_range',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching children in free-range programs (i.e. outside traditional classrooms)?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_children_in_schools',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching children in schools?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_students',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching college/university students?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_teens_free_range',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching teens in free-range programs (i.e. outside traditional classrooms)?'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='teaching_teens_in_schools',
            field=models.CharField(choices=[('none', 'None'), ('tens', 'Tens of hours'), ('hundreds', 'Hundreds of hours'), ('primary', 'Primary activity')], default='', max_length=50, verbose_name='How much time you have spent in the last five years teaching teens in schools?'),
        ),
    ]
