# Generated by Django 2.1 on 2018-10-25 16:05

from django.db import migrations, models


def migrate_rank(apps, schema_editor):
    RankingEntry = apps.get_model('ranker', 'RankingEntry')
    changes = {
        'essential': 'vimportant',
        'worthwhile': 'important',
        'unwise': 'vunimportant',
    }
    for k, v in changes.items():
        RankingEntry.objects.filter(rank=k).update(rank=v)


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0007_auto_20181004_1951'),
    ]

    operations = [
        migrations.RunPython(migrate_rank),
        migrations.AlterField(
            model_name='rankingentry',
            name='rank',
            field=models.CharField(choices=[('vunimportant', 'Very unimportant'), ('unimportant', 'Unimportant'), ('indifferent', 'Indifferent'), ('important', 'Important'), ('vimportant', 'Very important'), ('dont_understand', "I don't understand")], max_length=255, null=True, verbose_name='Selected rank'),
        ),
    ]
