# Generated by Django 2.1 on 2018-10-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0008_auto_20181025_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='category_stage1',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='category_stage2',
        ),
    ]
